//
// Generated by JTB 1.3.2
//

package st4tic.syntaxtree;

/**
 * Grammar production:
 * f0 -> "def"
 * f1 -> VariableName()
 * f2 -> "="
 * f3 -> MathExpression()
 * f4 -> "."
 */
public class VariableDeclaration implements Node {
   public NodeToken f0;
   public VariableName f1;
   public NodeToken f2;
   public MathExpression f3;
   public NodeToken f4;

   public VariableDeclaration(NodeToken n0, VariableName n1, NodeToken n2, MathExpression n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public VariableDeclaration(VariableName n0, MathExpression n1) {
      f0 = new NodeToken("def");
      f1 = n0;
      f2 = new NodeToken("=");
      f3 = n1;
      f4 = new NodeToken(".");
   }

   public void accept(st4tic.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(st4tic.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(st4tic.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(st4tic.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

