.TH "F:/Java/St4tic/st4tic/src/st4tic/visitor/GJVisitor.java" 3 "27 Dec 2009" "Version 1.0" "St4tic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Java/St4tic/st4tic/src/st4tic/visitor/GJVisitor.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBst4tic.visitor.GJVisitor< R, A >\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBst4tic.visitor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for St4tic from the source code.
