.TH "main::Main" 3 "27 Dec 2009" "Version 1.0" "St4tic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main::Main \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[]$)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBmain\fP for running St4tic language
.PP
\fBAuthor:\fP
.RS 4
Adrabi Abderrahim 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void main.Main.main (String $[])\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for St4tic from the source code.
