.TH "st4tic.visitor" 3 "27 Dec 2009" "Version 1.0" "St4tic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st4tic.visitor \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDepthFirstVisitor\fP"
.br
.ti -1c
.RI "class \fBGJDepthFirst< R, A >\fP"
.br
.ti -1c
.RI "class \fBGJNoArguDepthFirst< R >\fP"
.br
.ti -1c
.RI "interface \fBGJNoArguVisitor< R >\fP"
.br
.ti -1c
.RI "interface \fBGJVisitor< R, A >\fP"
.br
.ti -1c
.RI "class \fBGJVoidDepthFirst< A >\fP"
.br
.ti -1c
.RI "interface \fBGJVoidVisitor< A >\fP"
.br
.ti -1c
.RI "interface \fBVisitor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for St4tic from the source code.
