.TH "st4tic::core::St4ticValue" 3 "27 Dec 2009" "Version 1.0" "St4tic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st4tic::core::St4ticValue \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBst4tic::core::St4ticObject\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Class \fBgetType\fP ()"
.br
.ti -1c
.RI "void \fBsetType\fP (Class type)"
.br
.ti -1c
.RI "long \fBgetValue\fP ()"
.br
.ti -1c
.RI "void \fBsetValue\fP (long value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class base of \fBSt4tic\fP values
.PP
\fBAuthor:\fP
.RS 4
Adrabi Abderrahim 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Class st4tic.core.St4ticValue.getType ()"Get a value class type 
.PP
\fBReturns:\fP
.RS 4
Class 
.RE
.PP

.SS "long st4tic.core.St4ticValue.getValue ()"Get value as long (remember this language can operate just integers, if you don't know it please read the artile of this tutorial)
.PP
\fBReturns:\fP
.RS 4
long 
.RE
.PP

.SS "void st4tic.core.St4ticValue.setType (Class type)"Set value class type 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP 
.RE
.PP

.SS "void st4tic.core.St4ticValue.setValue (long value)"Set value as long 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for St4tic from the source code.
