.TH "st4tic::syntaxtree::NodeChoice" 3 "27 Dec 2009" "Version 1.0" "St4tic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st4tic::syntaxtree::NodeChoice \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBst4tic::syntaxtree::Node\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeChoice\fP (\fBNode\fP node)"
.br
.ti -1c
.RI "\fBNodeChoice\fP (\fBNode\fP node, int whichChoice)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBst4tic.visitor.Visitor\fP v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP \fBchoice\fP"
.br
.ti -1c
.RI "int \fBwhich\fP"
.br
.in -1c
.SS "Package Functions"

.in +1c
.ti -1c
.RI "public< R, A > R \fBaccept\fP (st4tic.visitor.GJVisitor< R, A > v, A argu)"
.br
.ti -1c
.RI "public< R > R \fBaccept\fP (st4tic.visitor.GJNoArguVisitor< R > v)"
.br
.ti -1c
.RI "public< A > void \fBaccept\fP (st4tic.visitor.GJVoidVisitor< A > v, A argu)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a grammar choice, e.g. ( A | B ) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "st4tic.syntaxtree.NodeChoice.NodeChoice (\fBNode\fP node)"
.SS "st4tic.syntaxtree.NodeChoice.NodeChoice (\fBNode\fP node, int whichChoice)"
.SH "Member Function Documentation"
.PP 
.SS "public<A> void st4tic.syntaxtree.NodeChoice.accept (st4tic.visitor.GJVoidVisitor< A > v, A argu)\fC [package]\fP"
.PP
Implements \fBst4tic.syntaxtree.Node\fP.
.SS "public<R> R st4tic.syntaxtree.NodeChoice.accept (st4tic.visitor.GJNoArguVisitor< R > v)\fC [package]\fP"
.PP
Implements \fBst4tic.syntaxtree.Node\fP.
.SS "public<R,A> R st4tic.syntaxtree.NodeChoice.accept (st4tic.visitor.GJVisitor< R, A > v, A argu)\fC [package]\fP"
.PP
Implements \fBst4tic.syntaxtree.Node\fP.
.SS "void st4tic.syntaxtree.NodeChoice.accept (\fBst4tic.visitor.Visitor\fP v)"
.PP
Implements \fBst4tic.syntaxtree.Node\fP.
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP \fBst4tic.syntaxtree.NodeChoice.choice\fP"
.SS "int \fBst4tic.syntaxtree.NodeChoice.which\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for St4tic from the source code.
