.TH "st4tic::core::St4ticObject" 3 "27 Dec 2009" "Version 1.0" "St4tic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st4tic::core::St4ticObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBst4tic.core.St4ticScope\fP, \fBst4tic.core.St4ticValue\fP, and \fBst4tic.core.St4ticVariable\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSt4ticObject\fP ()"
.br
.ti -1c
.RI "\fBSt4ticObject\fP (\fBSt4ticObject\fP parent)"
.br
.ti -1c
.RI "\fBSt4ticObject\fP \fBgetParent\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class base of all \fBSt4tic\fP language classes
.PP
\fBAuthor:\fP
.RS 4
Adrabi Abderrahim 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "st4tic.core.St4ticObject.St4ticObject ()"void constructor 
.SS "st4tic.core.St4ticObject.St4ticObject (\fBSt4ticObject\fP parent)"Constructor with parent object 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBSt4ticObject\fP st4tic.core.St4ticObject.getParent ()"Get an object parent 
.PP
\fBReturns:\fP
.RS 4
\fBSt4ticObject\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for St4tic from the source code.
